// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAONkuhkspuBkAAHCkRTf0TgNJT58E5xj8',
    appId: '1:377432063291:android:4cfeb64b76d4be914b4b1e',
    messagingSenderId: '377432063291',
    projectId: 'mymoviedb-1b64b',
    storageBucket: 'mymoviedb-1b64b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAylHfwegGoZ9DWVcZlpY-ARzyVlnfKWK8',
    appId: '1:377432063291:ios:5e895455047a57434b4b1e',
    messagingSenderId: '377432063291',
    projectId: 'mymoviedb-1b64b',
    storageBucket: 'mymoviedb-1b64b.appspot.com',
    iosClientId: '377432063291-fdc5qb6q4enb579k0pn18402poq9tmk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAylHfwegGoZ9DWVcZlpY-ARzyVlnfKWK8',
    appId: '1:377432063291:ios:4b35f2def6b7cf2c4b4b1e',
    messagingSenderId: '377432063291',
    projectId: 'mymoviedb-1b64b',
    storageBucket: 'mymoviedb-1b64b.appspot.com',
    iosClientId: '377432063291-tf4jruhv531vo25f469po3ilda465jo7.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
